using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Threading.Tasks;
using FluentAssertions;
using Serilog;
using WileyWidget.Models;
using WileyWidget.Services;
using Xunit;

namespace WileyWidget.WinForms.Tests.Unit.Services;

public sealed class ReportExportServiceTests : IDisposable
{
    private readonly string _testTempDir;
    private readonly ILogger _logger;
    private readonly ReportExportService _service;

    public ReportExportServiceTests()
    {
        _testTempDir = Path.Combine(Path.GetTempPath(), "WileyWidgetReportExportTests_" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_testTempDir);

        _logger = new LoggerConfiguration().CreateLogger();
        _service = new ReportExportService(_logger);
    }

    public void Dispose()
    {
        (_logger as IDisposable)?.Dispose();

        if (Directory.Exists(_testTempDir))
        {
            Directory.Delete(_testTempDir, true);
        }

        GC.SuppressFinalize(this);
    }

    [Fact]
    public async Task ExportToPdfAsync_WithBrandedReportDocument_CreatesPdfFile()
    {
        var filePath = Path.Combine(_testTempDir, "enterprise-vital-signs.pdf");

        await _service.ExportToPdfAsync(CreateDocument(), filePath);

        File.Exists(filePath).Should().BeTrue();
        new FileInfo(filePath).Length.Should().BeGreaterThan(0);
        ReadFilePrefix(filePath, 4).Should().Be("%PDF");
    }

    [Fact]
    public async Task ExportToExcelAsync_WithBrandedReportDocument_CreatesWorkbookFile()
    {
        var filePath = Path.Combine(_testTempDir, "enterprise-vital-signs.xlsx");

        await _service.ExportToExcelAsync(CreateDocument(), filePath);

        File.Exists(filePath).Should().BeTrue();
        new FileInfo(filePath).Length.Should().BeGreaterThan(0);
        ReadFilePrefix(filePath, 2).Should().Be("PK");
    }

    [Fact]
    public void TryGetReportLogoPath_FallsBackToBundledBranding_WhenCallerOmitsLogoPath()
    {
        var method = typeof(ReportExportService).GetMethod(
            "TryGetReportLogoPath",
            BindingFlags.NonPublic | BindingFlags.Static);

        method.Should().NotBeNull();

        var resolvedPath = method!.Invoke(null, [null]) as string;

        resolvedPath.Should().NotBeNullOrWhiteSpace();
        File.Exists(resolvedPath!).Should().BeTrue();
        Path.GetFileName(resolvedPath).Should().BeOneOf("wiley-brand-hero.jpg", "wiley-brand-hero.png", "wiley-report-logo.jpg", "wiley-report-logo.png");
    }

    private static ReportExportDocument CreateDocument()
    {
        return new ReportExportDocument(
            Title: "Enterprise Vital Signs",
            Subtitle: "Water, Sewer, Trash, and Apartments overview",
            GeneratedAt: new DateTime(2026, 3, 7, 9, 30, 0, DateTimeKind.Utc),
            GeneratedBy: "Generated by Wiley Widget and Grok",
            Branding: new ReportBrandingInfo(
                OrganizationName: "Town of Wiley",
                ApplicationName: "Wiley Widget",
                Attribution: "Generated by Wiley Widget and Grok"),
            Sections:
            [
                new ReportExportSection(
                    Title: "Enterprise Summary",
                    Columns: ["Enterprise", "Revenue", "Expenses", "Subsidy"],
                    Rows:
                    [
                        new Dictionary<string, string>
                        {
                            ["Enterprise"] = "Water",
                            ["Revenue"] = "$125,000",
                            ["Expenses"] = "$118,500",
                            ["Subsidy"] = "$0"
                        },
                        new Dictionary<string, string>
                        {
                            ["Enterprise"] = "Apartments",
                            ["Revenue"] = "$84,200",
                            ["Expenses"] = "$102,900",
                            ["Subsidy"] = "$18,700"
                        }
                    ])
            ],
            Metadata: new Dictionary<string, string>
            {
                ["Period"] = "FY2026 Q1",
                ["Scenario"] = "Baseline",
                ["Prepared For"] = "Town release candidate proof"
            });
    }

    private static string ReadFilePrefix(string filePath, int byteCount)
    {
        using var stream = File.OpenRead(filePath);
        var buffer = new byte[byteCount];
        var bytesRead = stream.Read(buffer, 0, buffer.Length);
        return System.Text.Encoding.ASCII.GetString(buffer, 0, bytesRead);
    }
}
