# Checkov configuration for Wiley Widget project
# This file controls checkov's infrastructure security scanning behavior

# Enable all security checks by default
framework:
  - json
  - yaml
  - dockerfile
  - terraform
  - cloudformation
  - kubernetes
  - arm
  - bicep
  - github_actions

# Skip these checks to reduce noise and focus on critical security issues
skip-check:
  # GitHub Actions - Skip some overly strict checks
  - CKV_GHA_1 # Ensure GITHUB_TOKEN permissions are restricted (too strict for dev workflows)

  # JSON/YAML - Skip formatting checks (handled by prettier)
  - CKV_JSON_1 # JSON syntax validation (handled by other tools)

  # Azure ARM/Bicep - Skip some development-specific checks
  - CKV_AZURE_1 # Ensure that 'Secure transfer required' is set (dev environments)

# Only scan these file types to prevent performance issues
file-type:
  - json
  - yaml
  - yml
  - dockerfile
  - tf
  - bicep
  - arm

# Exclude directories and files that don't need infrastructure security scanning
exclude-paths:
  - .git/
  - .trunk/
  - .vscode/
  - .vs/
  - bin/
  - obj/
  - node_modules/
  - .venv/
  - venv/
  - TestResults/
  - coverage/
  - logs/
  - docs/
  - __pycache__/
  - .pytest_cache/
  - "*.log"
  - "*.cache"
  - "*.tmp"
  - "*.bak"
  - "*.backup"
  - "**/*test*.json" # Skip test configuration files
  - "**/*example*.json" # Skip example files
  - "**/*sample*.json" # Skip sample files

# Focus on high and medium severity issues
check-type:
  - HIGH
  - MEDIUM

# Output format optimized for CI/CD and human reading
output-format:
  - cli
  - sarif

# Enable compact output to reduce log verbosity
compact: true

# Don't download external modules (for performance)
download-external-modules: false
# Set baseline for existing issues (optional - can be generated with --create-baseline)
# baseline: .checkov.baseline

# Custom policies directory (if you want to add project-specific checks)
# external-checks-dir: .checkov/custom-policies/
