// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WileyWidget.Data;

#nullable disable

namespace WileyWidget.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("WileyWidget.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoSaveIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CacheExpirationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrencyFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentFiscalYear")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseServer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableAI")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableAutoSave")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableDataCaching")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableFileLogging")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableQuickBooksSync")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSounds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FiscalPeriod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FiscalQuarter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FiscalYearEnd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FiscalYearStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FiscalYearStartDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiscalYearStartMonth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeChartsInReports")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastReportEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastReportStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastSelectedEnterpriseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastSelectedFormat")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSelectedReportType")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QboAccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("QboClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QboClientSecret")
                        .HasColumnType("TEXT");

                    b.Property<string>("QboRefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("QboTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuickBooksAccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuickBooksCompanyFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuickBooksEnvironment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuickBooksRealmId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuickBooksRedirectUri")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuickBooksRefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("QuickBooksTokenExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedLogLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionTimeoutMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseDynamicColumns")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseFiscalYearForReporting")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("WindowHeight")
                        .HasColumnType("REAL");

                    b.Property<double?>("WindowLeft")
                        .HasColumnType("REAL");

                    b.Property<bool?>("WindowMaximized")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("WindowTop")
                        .HasColumnType("REAL");

                    b.Property<double?>("WindowWidth")
                        .HasColumnType("REAL");

                    b.Property<string>("XaiApiEndpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("XaiApiKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("XaiMaxTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("XaiModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("XaiTemperature")
                        .HasColumnType("REAL");

                    b.Property<int>("XaiTimeout")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("WileyWidget.Models.AuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Changes")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("WileyWidget.Models.BudgetEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActualAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BudgetedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EncumbranceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndPeriod")
                        .HasColumnType("TEXT");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FundId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FundType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGASBCompliant")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MunicipalAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceRowNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartPeriod")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Variance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FundId");

                    b.HasIndex("MunicipalAccountId");

                    b.HasIndex("ParentId");

                    b.ToTable("BudgetEntries");
                });

            modelBuilder.Entity("WileyWidget.Models.BudgetInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InteractionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCost")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrimaryEnterpriseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SecondaryEnterpriseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryEnterpriseId");

                    b.HasIndex("SecondaryEnterpriseId");

                    b.ToTable("BudgetInteraction");
                });

            modelBuilder.Entity("WileyWidget.Models.BudgetPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BudgetPeriods");
                });

            modelBuilder.Entity("WileyWidget.Models.Charge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChargeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("Charges");
                });

            modelBuilder.Entity("WileyWidget.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("WileyWidget.Models.Enterprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BudgetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CitizenCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MeterReadDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MeterReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PreviousMeterReadDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PreviousMeterReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Enterprises");
                });

            modelBuilder.Entity("WileyWidget.Models.Entities.Fund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FundCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Funds");
                });

            modelBuilder.Entity("WileyWidget.Models.FiscalYearSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiscalYearStartDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiscalYearStartMonth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("FiscalYearSettings");
                });

            modelBuilder.Entity("WileyWidget.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MunicipalAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("VendorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MunicipalAccountId");

                    b.HasIndex("VendorId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("WileyWidget.Models.MunicipalAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber_Value")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BudgetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BudgetPeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fund")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FundDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuickBooksId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BudgetPeriodId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ParentAccountId");

                    b.ToTable("MunicipalAccounts");
                });

            modelBuilder.Entity("WileyWidget.Models.TaxRevenueSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BudgetYearAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BudgetYearLevy")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentYearAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentYearLevy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IncDecAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IncDecLevy")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriorYearAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriorYearLevy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TaxRevenueSummaries");
                });

            modelBuilder.Entity("WileyWidget.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BudgetEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MunicipalAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BudgetEntryId");

                    b.HasIndex("MunicipalAccountId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("WileyWidget.Models.UtilityBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentMeterReading")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GarbageCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LateFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OtherCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PreviousMeterReading")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<decimal>("SewerCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StormwaterCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WaterCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WaterUsageGallons")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("UtilityBills");
                });

            modelBuilder.Entity("WileyWidget.Models.UtilityCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AccountCloseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AccountOpenDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessLicenseNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConnectDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DisconnectDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LastPaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastPaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingAddress")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingCity")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingState")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailingZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("MeterNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("ServiceAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceLocation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceState")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UtilityCustomers");
                });

            modelBuilder.Entity("WileyWidget.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("WileyWidget.Models.BudgetEntry", b =>
                {
                    b.HasOne("WileyWidget.Models.Department", "Department")
                        .WithMany("BudgetEntries")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WileyWidget.Models.Entities.Fund", "Fund")
                        .WithMany("BudgetEntries")
                        .HasForeignKey("FundId");

                    b.HasOne("WileyWidget.Models.MunicipalAccount", "MunicipalAccount")
                        .WithMany("BudgetEntries")
                        .HasForeignKey("MunicipalAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WileyWidget.Models.BudgetEntry", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Department");

                    b.Navigation("Fund");

                    b.Navigation("MunicipalAccount");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("WileyWidget.Models.BudgetInteraction", b =>
                {
                    b.HasOne("WileyWidget.Models.Enterprise", "PrimaryEnterprise")
                        .WithMany("BudgetInteractions")
                        .HasForeignKey("PrimaryEnterpriseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WileyWidget.Models.Enterprise", "SecondaryEnterprise")
                        .WithMany()
                        .HasForeignKey("SecondaryEnterpriseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PrimaryEnterprise");

                    b.Navigation("SecondaryEnterprise");
                });

            modelBuilder.Entity("WileyWidget.Models.Charge", b =>
                {
                    b.HasOne("WileyWidget.Models.UtilityBill", "Bill")
                        .WithMany("Charges")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("WileyWidget.Models.Department", b =>
                {
                    b.HasOne("WileyWidget.Models.Department", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("WileyWidget.Models.Invoice", b =>
                {
                    b.HasOne("WileyWidget.Models.MunicipalAccount", "MunicipalAccount")
                        .WithMany("Invoices")
                        .HasForeignKey("MunicipalAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WileyWidget.Models.Vendor", "Vendor")
                        .WithMany("Invoices")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MunicipalAccount");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("WileyWidget.Models.MunicipalAccount", b =>
                {
                    b.HasOne("WileyWidget.Models.BudgetPeriod", "BudgetPeriod")
                        .WithMany("Accounts")
                        .HasForeignKey("BudgetPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WileyWidget.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WileyWidget.Models.MunicipalAccount", "ParentAccount")
                        .WithMany("ChildAccounts")
                        .HasForeignKey("ParentAccountId");

                    b.OwnsOne("WileyWidget.Models.AccountNumber", "AccountNumber", b1 =>
                        {
                            b1.Property<int>("MunicipalAccountId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.HasKey("MunicipalAccountId");

                            b1.ToTable("MunicipalAccounts", t =>
                                {
                                    t.Property("Value")
                                        .HasColumnName("AccountNumber_Value1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("MunicipalAccountId");
                        });

                    b.Navigation("AccountNumber")
                        .IsRequired();

                    b.Navigation("BudgetPeriod");

                    b.Navigation("Department");

                    b.Navigation("ParentAccount");
                });

            modelBuilder.Entity("WileyWidget.Models.Transaction", b =>
                {
                    b.HasOne("WileyWidget.Models.BudgetEntry", "BudgetEntry")
                        .WithMany("Transactions")
                        .HasForeignKey("BudgetEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WileyWidget.Models.MunicipalAccount", null)
                        .WithMany("Transactions")
                        .HasForeignKey("MunicipalAccountId");

                    b.Navigation("BudgetEntry");
                });

            modelBuilder.Entity("WileyWidget.Models.UtilityBill", b =>
                {
                    b.HasOne("WileyWidget.Models.UtilityCustomer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WileyWidget.Models.BudgetEntry", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("WileyWidget.Models.BudgetPeriod", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("WileyWidget.Models.Department", b =>
                {
                    b.Navigation("BudgetEntries");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("WileyWidget.Models.Enterprise", b =>
                {
                    b.Navigation("BudgetInteractions");
                });

            modelBuilder.Entity("WileyWidget.Models.Entities.Fund", b =>
                {
                    b.Navigation("BudgetEntries");
                });

            modelBuilder.Entity("WileyWidget.Models.MunicipalAccount", b =>
                {
                    b.Navigation("BudgetEntries");

                    b.Navigation("ChildAccounts");

                    b.Navigation("Invoices");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("WileyWidget.Models.UtilityBill", b =>
                {
                    b.Navigation("Charges");
                });

            modelBuilder.Entity("WileyWidget.Models.Vendor", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
