# Docker Compose for running xUnit tests
version: "3.8"

services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./TestResults:/test-results
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    command:
      [
        "dotnet",
        "test",
        "WileyWidget.Tests/WileyWidget.Tests.csproj",
        "--configuration",
        "Release",
        "--logger",
        "trx",
        "--results-directory",
        "/test-results",
        "--no-build",
        "--verbosity",
        "normal",
      ]
