# Gitleaks Configuration for Wiley Widget
# https://github.com/gitleaks/gitleaks

# Title for the configuration
title: "Wiley Widget Security Scan"

# Global allowlist for false positives
allowlist:
  # Allowlist for file paths
  paths:
    - "^\\.trunk/"
    - "^bin/"
    - "^obj/"
    - "^TestResults/"
    - "^coverage/"
    - "^.*\\.binlog$"
    - "^.*\\.exe$"
    - "^.*\\.dll$"
    - "^.*\\.tmp$"
    - "^.*\\.log$"
    - "^.*\\.bak$"
    - "^.*\\.backup$"

  # Allowlist for commits
  commits:
    - "^(feat|fix|docs|style|refactor|test|chore):"
    - "^Merge branch"
    - "^Merge pull request"

  # Allowlist for regex patterns (false positives)
  regexes:
    - "example"
    - "test"
    - "sample"
    - "dummy"
    - "placeholder"
    - "your-.*-here"

# Custom rules for specific patterns
rules:
  # Generic API Key
  - id: "generic-api-key"
    description: "Generic API Key"
    regex: "(?i)(api[_-]?key|apikey)([\\s\\S]{0,10})?[=:]([\\s\\S]{0,100})"
    tags:
      - key
      - API
    entropy: 3.5
    secretGroup: 3
    allowlist:
      paths:
        - "^.*\\.md$"
        - "^.*\\.txt$"
        - "^.*\\.example$"

  # Azure Connection Strings
  - id: "azure-connection-string"
    description: "Azure Connection String"
    regex: "(?i)(DefaultEndpointsProtocol|AccountName|AccountKey|BlobEndpoint|QueueEndpoint|TableEndpoint|FileEndpoint)"
    tags:
      - azure
      - connection
      - cloud
    entropy: 4.0

  # Database Connection Strings
  - id: "database-connection"
    description: "Database Connection String"
    regex: "(?i)(server|host|database|username|password|connection.*string)"
    tags:
      - database
      - connection
    entropy: 3.0
    allowlist:
      paths:
        - "^.*\\.config$"
        - "^.*\\.json$"
        - "^appsettings.*\\.json$"

  # JWT Tokens
  - id: "jwt-token"
    description: "JWT Token"
    regex: "eyJ[A-Za-z0-9+/]+=*[A-Za-z0-9+/]*"
    tags:
      - jwt
      - token
      - authentication

  # Private Keys
  - id: "private-key"
    description: "Private Key"
    regex: "-----BEGIN [A-Z ]*PRIVATE KEY-----"
    tags:
      - key
      - private
      - crypto

  # AWS Access Keys
  - id: "aws-access-key"
    description: "AWS Access Key"
    regex: "(?i)AKIA[0-9A-Z]{16}"
    tags:
      - aws
      - key
      - cloud

  # Generic Passwords
  - id: "generic-password"
    description: "Generic Password Pattern"
    regex: "(?i)(password|passwd|pwd)[\\s\\S]{0,10}[=:]([\\s\\S]{0,50})"
    tags:
      - password
      - credential
    entropy: 3.0
    allowlist:
      paths:
        - "^.*\\.md$"
        - "^.*\\.txt$"
        - "^.*\\.example$"
        - "^.*\\.sample$"

# Extend default rules with custom allowlist
extend:
  # Use default gitleaks rules but with our custom allowlist
  useDefaultRules: true

# Output configuration
output:
  format: "json"
  path: ".trunk/out/gitleaks-results.json"
  redacted: true

# Performance settings
performance:
  maxTargetMegaBytes: 100
  regexTimeout: 30

# Verbosity level
verbose: true
