#nullable enable

using System.Collections.ObjectModel;
using WileyWidget.Models;
using WileyWidget.WinForms.Models;

namespace WileyWidget.WinForms.ViewModels
{
    /// <summary>
    /// Interface for the Accounts ViewModel.
    /// Defines the contract for managing municipal accounts with filtering and CRUD operations.
    /// Excludes auto-generated RelayCommand properties since they're generated by MVVM Toolkit.
    /// </summary>
    public interface IAccountsViewModel : System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>Gets or sets the title of the view.</summary>
        string Title { get; set; }

        /// <summary>Gets or sets whether accounts are currently loading.</summary>
        bool IsLoading { get; set; }

        /// <summary>Gets or sets the collection of municipal accounts.</summary>
        ObservableCollection<MunicipalAccountDisplay> Accounts { get; set; }

        /// <summary>Gets or sets the selected fund filter.</summary>
        MunicipalFundType? SelectedFund { get; set; }

        /// <summary>Gets or sets the selected account type filter.</summary>
        AccountType? SelectedAccountType { get; set; }

        /// <summary>Gets or sets the search text for filtering.</summary>
        string? SearchText { get; set; }

        /// <summary>Gets the collection of available fund types.</summary>
        ObservableCollection<MunicipalFundType> AvailableFunds { get; }

        /// <summary>Gets the collection of available account types.</summary>
        ObservableCollection<AccountType> AvailableAccountTypes { get; }

        /// <summary>Gets or sets the total balance across all accounts.</summary>
        decimal TotalBalance { get; set; }

        /// <summary>Gets or sets the count of active accounts.</summary>
        int ActiveAccountCount { get; set; }

        /// <summary>Gets or sets the selected account.</summary>
        MunicipalAccountDisplay? SelectedAccount { get; set; }

        /// <summary>Gets or sets the error message.</summary>
        string? ErrorMessage { get; set; }

        /// <summary>Gets or sets the status text.</summary>
        string? StatusText { get; set; }
    }
}
