#nullable enable

using System.Collections.ObjectModel;
using WileyWidget.Models;

namespace WileyWidget.WinForms.ViewModels
{
    /// <summary>
    /// Interface for the AI Chat ViewModel.
    /// Defines the contract for managing chat messages, AI tool execution, and personality management.
    /// Excludes auto-generated RelayCommand properties since they're generated by MVVM Toolkit.
    /// </summary>
    public interface IAIChatViewModel : System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Collection of chat messages in the conversation.
        /// </summary>
        ObservableCollection<ChatMessage> Messages { get; set; }

        /// <summary>
        /// Current user input text.
        /// </summary>
        string InputText { get; set; }

        /// <summary>
        /// Selected tool for manual tool selection.
        /// </summary>
        string? SelectedTool { get; set; }

        /// <summary>
        /// Available tools for selection.
        /// </summary>
        ObservableCollection<string> AvailableTools { get; set; }

        /// <summary>
        /// Indicates whether a message is being processed.
        /// </summary>
        bool IsLoading { get; set; }

        /// <summary>
        /// Status text for the progress panel.
        /// </summary>
        string StatusText { get; set; }

        /// <summary>
        /// Error message if an operation fails.
        /// </summary>
        string? ErrorMessage { get; set; }

        /// <summary>
        /// Number of messages in the conversation.
        /// </summary>
        int MessageCount { get; set; }

        /// <summary>
        /// Indicates whether conversational AI fallback is available.
        /// </summary>
        bool HasConversationalAI { get; set; }

        /// <summary>
        /// Current personality name for AI responses.
        /// </summary>
        string CurrentPersonality { get; set; }
    }
}
