#nullable enable

using System.Collections.ObjectModel;
using WileyWidget.Services.Abstractions;

namespace WileyWidget.WinForms.ViewModels
{
    // ...existing code...
    /// <summary>
    /// Interface for the Analytics ViewModel.
    /// Defines the contract for analytics functionality with exploratory analysis, scenario modeling, and forecasting.
    /// Excludes auto-generated RelayCommand properties since they're generated by MVVM Toolkit.
    /// Note: Collection type specifics are abstracted to avoid exposing internal model dependencies.
    /// </summary>
    public interface IAnalyticsViewModel : System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>Indicates whether data is currently being loaded or processed.</summary>
        bool IsLoading { get; set; }

        /// <summary>Current status text displayed to the user.</summary>
        string StatusText { get; set; }

        /// <summary>Collection of analytics metrics.</summary>
        ObservableCollection<AnalyticsMetric> Metrics { get; set; }

        /// <summary>Collection of top variance analyses.</summary>
        ObservableCollection<VarianceAnalysis> TopVariances { get; set; }

        /// <summary>Collection of monthly trend data.</summary>
        ObservableCollection<MonthlyTrend> TrendData { get; set; }

        /// <summary>Collection of yearly projections from scenario analysis.</summary>
        ObservableCollection<YearlyProjection> ScenarioProjections { get; set; }

        /// <summary>Collection of forecast data points.</summary>
        ObservableCollection<ForecastPoint> ForecastData { get; set; }

        /// <summary>Collection of key insights from exploratory analysis.</summary>
        ObservableCollection<string> Insights { get; set; }

        /// <summary>Collection of recommendations from analysis.</summary>
        ObservableCollection<string> Recommendations { get; set; }

        /// <summary>Rate increase percentage for scenario modeling.</summary>
        decimal RateIncreasePercentage { get; set; }

        /// <summary>Expense increase percentage for scenario modeling.</summary>
        decimal ExpenseIncreasePercentage { get; set; }

        /// <summary>Revenue target increase percentage for scenario modeling.</summary>
        decimal RevenueTargetPercentage { get; set; }

        /// <summary>Number of years to project for forecasting.</summary>
        int ProjectionYears { get; set; }

        /// <summary>Total budgeted amount across all analyzed accounts.</summary>
        decimal TotalBudgetedAmount { get; set; }

        /// <summary>Total actual amount across all analyzed accounts.</summary>
        decimal TotalActualAmount { get; set; }

        /// <summary>Total variance amount.</summary>
        decimal TotalVarianceAmount { get; set; }

        /// <summary>Average variance percentage across all analyzed accounts.</summary>
        decimal AverageVariancePercentage { get; set; }

        /// <summary>Detailed explanation of recommendations.</summary>
        string RecommendationExplanation { get; set; }

        /// <summary>Filtered collection of metrics based on search criteria.</summary>
        ObservableCollection<AnalyticsMetric> FilteredMetrics { get; set; }

        /// <summary>Filtered collection of variances based on search criteria.</summary>
        ObservableCollection<VarianceAnalysis> FilteredTopVariances { get; set; }

        /// <summary>Search text for filtering metrics.</summary>
        string MetricsSearchText { get; set; }

        /// <summary>Search text for filtering variances.</summary>
        string VariancesSearchText { get; set; }
    }
}
