#nullable enable

using System.Collections.ObjectModel;
using WileyWidget.Models;

namespace WileyWidget.WinForms.ViewModels
{
    /// <summary>
    /// Interface for the Budget ViewModel.
    /// Defines the contract for budget management with CRUD operations, filtering, and analysis.
    /// Excludes auto-generated RelayCommand properties since they're generated by MVVM Toolkit.
    /// </summary>
    public interface IBudgetViewModel : System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>Collection of all budget entries.</summary>
        ObservableCollection<BudgetEntry> BudgetEntries { get; set; }

        /// <summary>Filtered collection of budget entries.</summary>
        ObservableCollection<BudgetEntry> FilteredBudgetEntries { get; set; }

        /// <summary>Selected budget period.</summary>
        BudgetPeriod? SelectedPeriod { get; set; }

        /// <summary>Selected fiscal year for filtering.</summary>
        int SelectedFiscalYear { get; set; }

        /// <summary>Current error message.</summary>
        string ErrorMessage { get; set; }

        /// <summary>Indicates whether data is loading.</summary>
        bool IsLoading { get; set; }

        /// <summary>Current status text.</summary>
        string StatusText { get; set; }

        /// <summary>Search text for filtering entries.</summary>
        string SearchText { get; set; }

        /// <summary>Selected department ID filter.</summary>
        int? SelectedDepartmentId { get; set; }

        /// <summary>Selected fund type filter.</summary>
        FundType? SelectedFundType { get; set; }

        /// <summary>Minimum variance threshold filter.</summary>
        decimal? VarianceThreshold { get; set; }

        /// <summary>Show only over-budget entries.</summary>
        bool ShowOnlyOverBudget { get; set; }

        /// <summary>Show only under-budget entries.</summary>
        bool ShowOnlyUnderBudget { get; set; }

        /// <summary>Total budgeted amount across all entries.</summary>
        decimal TotalBudgeted { get; set; }

        /// <summary>Total actual spent amount across all entries.</summary>
        decimal TotalActual { get; set; }

        /// <summary>Total variance amount.</summary>
        decimal TotalVariance { get; set; }

        /// <summary>Total encumbrance amount across all entries.</summary>
        decimal TotalEncumbrance { get; set; }

        /// <summary>Percentage of budget used.</summary>
        decimal PercentUsed { get; set; }

        /// <summary>Count of entries over budget.</summary>
        int EntriesOverBudget { get; set; }

        /// <summary>Count of entries under budget.</summary>
        int EntriesUnderBudget { get; set; }

        /// <summary>Field name to group entries by.</summary>
        string GroupBy { get; set; }

        /// <summary>Display entries in hierarchical view.</summary>
        bool ShowHierarchy { get; set; }
    }
}
