#nullable enable

using System;
using System.Collections.ObjectModel;
using WileyWidget.WinForms.Models;

namespace WileyWidget.WinForms.ViewModels
{
    /// <summary>
    /// Interface for the BudgetOverviewViewModel.
    /// Defines the contract for dependency injection and testability.
    /// Excludes auto-generated RelayCommand properties since they're generated by MVVM Toolkit.
    /// </summary>
    public interface IBudgetOverviewViewModel : System.ComponentModel.INotifyPropertyChanged
    {
        ObservableCollection<object> Categories { get; set; }
        ObservableCollection<int> AvailableFiscalYears { get; set; }
        ObservableCollection<object> Metrics { get; set; }
        int FiscalYear { get; set; }
        object? SelectedCategory { get; set; }
        decimal TotalBudget { get; set; }
        decimal TotalActual { get; set; }
        decimal TotalEncumbrance { get; set; }
        decimal TotalVariance { get; set; }
        decimal OverallVariancePercent { get; set; }
        int OverBudgetCount { get; set; }
        int UnderBudgetCount { get; set; }
        DateTime LastUpdated { get; set; }
        bool IsLoading { get; set; }
        string? ErrorMessage { get; set; }
    }
}
