#nullable enable

using System;
using System.Collections.ObjectModel;
using WileyWidget.Models;

namespace WileyWidget.WinForms.ViewModels
{
    /// <summary>
    /// Interface for the CustomersViewModel.
    /// Defines the contract for dependency injection and testability.
    /// Excludes auto-generated RelayCommand properties since they're generated by MVVM Toolkit.
    /// </summary>
    public interface ICustomersViewModel : System.ComponentModel.INotifyPropertyChanged
    {
        ObservableCollection<UtilityCustomer> Customers { get; set; }
        UtilityCustomer? SelectedCustomer { get; set; }
        bool IsLoading { get; set; }
        string? ErrorMessage { get; set; }
        string StatusText { get; set; }
    }
}
