#nullable enable

using System;
using System.Collections.ObjectModel;
using WileyWidget.Models;

namespace WileyWidget.WinForms.ViewModels
{
    /// <summary>
    /// Interface for the Dashboard ViewModel.
    /// Defines the contract for comprehensive dashboard metric display and data loading.
    /// Excludes auto-generated RelayCommand properties since they're generated by MVVM Toolkit.
    /// </summary>
    public interface IDashboardViewModel : System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>Name of the municipality.</summary>
        string MunicipalityName { get; set; }

        /// <summary>Current fiscal year display string.</summary>
        string FiscalYear { get; set; }

        /// <summary>Timestamp of last data update.</summary>
        DateTime LastUpdated { get; set; }

        /// <summary>Indicates whether data is currently loading.</summary>
        bool IsLoading { get; set; }

        /// <summary>Indicates whether an error state is active.</summary>
        bool HasError { get; set; }

        /// <summary>Error message if an error occurred.</summary>
        string? ErrorMessage { get; set; }

        /// <summary>Collection of dashboard metrics.</summary>
        ObservableCollection<DashboardMetric> Metrics { get; set; }

        /// <summary>Gauge value (0-100) for total budget usage.</summary>
        float TotalBudgetGauge { get; set; }

        /// <summary>Gauge value (0-100) for revenue.</summary>
        float RevenueGauge { get; set; }

        /// <summary>Gauge value (0-100) for expenses.</summary>
        float ExpensesGauge { get; set; }

        /// <summary>Gauge value (0-100) for net position.</summary>
        float NetPositionGauge { get; set; }

        /// <summary>Budget variance analysis results.</summary>
        BudgetVarianceAnalysis? BudgetAnalysis { get; set; }

        /// <summary>Total budgeted amount for current fiscal year.</summary>
        decimal TotalBudgeted { get; set; }

        /// <summary>Total actual spent amount for current fiscal year.</summary>
        decimal TotalActual { get; set; }

        /// <summary>Total variance amount (Budgeted - Actual).</summary>
        decimal TotalVariance { get; set; }

        /// <summary>Overall variance percentage.</summary>
        decimal VariancePercentage { get; set; }

        /// <summary>Collection of fund summaries by fund type.</summary>
        ObservableCollection<FundSummary> FundSummaries { get; set; }

        /// <summary>Collection of department-level summaries.</summary>
        ObservableCollection<DepartmentSummary> DepartmentSummaries { get; set; }

        /// <summary>Collection of top accounts by variance.</summary>
        ObservableCollection<AccountVariance> TopVariances { get; set; }

        /// <summary>Total revenue collected.</summary>
        decimal TotalRevenue { get; set; }

        /// <summary>Total expenses incurred.</summary>
        decimal TotalExpenses { get; set; }

        /// <summary>Net income (Revenue - Expenses).</summary>
        decimal NetIncome { get; set; }

        /// <summary>Count of active accounts.</summary>
        int AccountCount { get; set; }

        /// <summary>Count of active departments.</summary>
        int ActiveDepartments { get; set; }

        /// <summary>Collection of monthly revenue data for charts.</summary>
        ObservableCollection<MonthlyRevenue> MonthlyRevenueData { get; set; }

        /// <summary>Collection of monthly budget vs actual data for charting.</summary>
        ObservableCollection<MonthlyBudgetSummary> MonthlySummaries { get; set; }

        /// <summary>Current status text for display.</summary>
        string StatusText { get; set; }

        /// <summary>Timestamp of last refresh operation.</summary>
        DateTime? LastRefreshTime { get; set; }
    }
}
