#nullable enable

using System;
using System.Collections.ObjectModel;

namespace WileyWidget.WinForms.ViewModels
{
    /// <summary>
    /// Interface for the DepartmentSummaryViewModel.
    /// Defines the contract for dependency injection and testability.
    /// Excludes auto-generated RelayCommand properties since they're generated by MVVM Toolkit.
    /// </summary>
    public interface IDepartmentSummaryViewModel : System.ComponentModel.INotifyPropertyChanged
    {
        ObservableCollection<object> Departments { get; set; }
        object? SelectedDepartment { get; set; }
        bool IsLoading { get; set; }
        string? ErrorMessage { get; set; }
        string StatusText { get; set; }
        decimal TotalBudget { get; set; }
        decimal TotalActual { get; set; }
    }
}
