#nullable enable

using System;
using System.Collections.ObjectModel;

namespace WileyWidget.WinForms.ViewModels
{
    /// <summary>
    /// Interface for the QuickBooksViewModel.
    /// Defines the contract for dependency injection and testability.
    /// Excludes auto-generated RelayCommand properties since they're generated by MVVM Toolkit.
    /// </summary>
    public interface IQuickBooksViewModel : System.ComponentModel.INotifyPropertyChanged
    {
        bool IsLoading { get; set; }
        bool IsConnected { get; set; }
        string ConnectionStatus { get; set; }
        string? ErrorMessage { get; set; }
        string StatusText { get; set; }

        /// <summary>Runs sandbox connection diagnostics and returns a formatted report string.</summary>
        System.Threading.Tasks.Task<string> RunDiagnosticsAsync(System.Threading.CancellationToken cancellationToken = default);
    }
}
