#nullable enable

using System;
using System.Collections.ObjectModel;

namespace WileyWidget.WinForms.ViewModels
{
    /// <summary>
    /// Interface for the RevenueTrendsViewModel.
    /// Defines the contract for dependency injection and testability.
    /// Excludes auto-generated RelayCommand properties since they're generated by MVVM Toolkit.
    /// </summary>
    public interface IRevenueTrendsViewModel : System.ComponentModel.INotifyPropertyChanged
    {
        ObservableCollection<object> TrendData { get; set; }
        bool IsLoading { get; set; }
        string? ErrorMessage { get; set; }
        string StatusText { get; set; }
        decimal TotalRevenue { get; set; }
        decimal AverageMonthlyRevenue { get; set; }
    }
}
