#nullable enable

using System;
using System.Collections.ObjectModel;

namespace WileyWidget.WinForms.ViewModels
{
    /// <summary>
    /// Interface for the SettingsViewModel.
    /// Defines the contract for dependency injection and testability.
    /// Excludes auto-generated RelayCommand properties since they're generated by MVVM Toolkit.
    /// </summary>
    public interface ISettingsViewModel : System.ComponentModel.INotifyPropertyChanged
    {
        string ThemeName { get; set; }
        bool EnableNotifications { get; set; }
        bool EnableAutoSave { get; set; }
        bool IsLoading { get; set; }
        string? ErrorMessage { get; set; }
        string StatusText { get; set; }
    }
}
