#nullable enable

using System;
using System.Collections.ObjectModel;
using WileyWidget.Models;

namespace WileyWidget.WinForms.ViewModels
{
    /// <summary>
    /// Interface for the UtilityBillViewModel.
    /// Defines the contract for dependency injection and testability.
    /// Excludes auto-generated RelayCommand properties since they're generated by MVVM Toolkit.
    /// </summary>
    public interface IUtilityBillViewModel : System.ComponentModel.INotifyPropertyChanged
    {
        ObservableCollection<UtilityBill> Bills { get; set; }
        UtilityBill? SelectedBill { get; set; }
        bool IsLoading { get; set; }
        string? ErrorMessage { get; set; }
        string StatusText { get; set; }
        decimal TotalAmount { get; set; }
    }
}
