#nullable enable

using System;
using System.Collections.ObjectModel;

namespace WileyWidget.WinForms.ViewModels
{
    /// <summary>
    /// Interface for the WarRoomViewModel.
    /// Defines the contract for dependency injection and testability.
    /// Excludes auto-generated RelayCommand properties since they're generated by MVVM Toolkit.
    /// </summary>
    public interface IWarRoomViewModel : System.ComponentModel.INotifyPropertyChanged
    {
        ObservableCollection<object> Alerts { get; set; }
        object? SelectedAlert { get; set; }
        bool IsLoading { get; set; }
        string? ErrorMessage { get; set; }
        string StatusText { get; set; }
        int CriticalAlertCount { get; set; }
    }
}
