# Configuration Lock-In Script
# This script creates a robust, corruption-resistant configuration system

param(
    [switch]$LockIn,
    [switch]$Verify,
    [switch]$Reset,
    [switch]$Monitor
)

Write-Host "🔒 Configuration Lock-In System" -ForegroundColor Cyan
Write-Host "===============================" -ForegroundColor Cyan

# Configuration constants
$CONFIG = @{
    VaultName = "wiley-widget-secrets"
    ResourceGroup = "WileyWidgetRG"
    Secrets = @{
        "SYNCFUSION-LICENSE-KEY" = "SYNCFUSION_LICENSE_KEY"
        "XAI-API-KEY" = "XAI_API_KEY"
        "GITHUB-PAT" = "GITHUB_TOKEN"
    }
    LockFile = ".config-lock.json"
    BackupDir = ".config-backups"
}

function Test-AzureConnection {
    Write-Host "Testing Azure connection..." -ForegroundColor Yellow
    try {
        $account = az account show --query "user.name" -o tsv 2>$null
        if ($LASTEXITCODE -ne 0) {
            throw "Not authenticated with Azure CLI"
        }
        Write-Host "✅ Azure authenticated as: $account" -ForegroundColor Green
        return $true
    } catch {
        Write-Host "❌ Azure authentication failed: $($_.Exception.Message)" -ForegroundColor Red
        return $false
    }
}

function Get-SecretsFromVault {
    Write-Host "Retrieving secrets from Key Vault..." -ForegroundColor Yellow

    $secrets = @{}
    foreach ($kvSecret in $CONFIG.Secrets.Keys) {
        try {
            $value = az keyvault secret show --vault-name $CONFIG.VaultName --name $kvSecret --query value -o tsv 2>$null
            if ($LASTEXITCODE -eq 0 -and $value) {
                $envVar = $CONFIG.Secrets[$kvSecret]
                $secrets[$envVar] = $value
                Write-Host "  ✅ Retrieved $envVar ($($value.Length) chars)" -ForegroundColor Green
            } else {
                Write-Host "  ❌ Failed to retrieve $kvSecret" -ForegroundColor Red
            }
        } catch {
            Write-Host "  ❌ Error retrieving $kvSecret : $($_.Exception.Message)" -ForegroundColor Red
        }
    }

    return $secrets
}

function Set-EnvironmentVariables {
    param([hashtable]$Secrets)

    Write-Host "Setting environment variables..." -ForegroundColor Yellow

    foreach ($envVar in $Secrets.Keys) {
        $value = $Secrets[$envVar]
        [Environment]::SetEnvironmentVariable($envVar, $value, "Process")
        Write-Host "  ✅ Set $envVar in Process scope" -ForegroundColor Green
    }
}

function Update-EnvFile {
    param([hashtable]$Secrets)

    Write-Host "Updating .env file..." -ForegroundColor Yellow

    # Create backup
    if (Test-Path ".env") {
        $backupDir = $CONFIG.BackupDir
        if (!(Test-Path $backupDir)) {
            New-Item -ItemType Directory -Path $backupDir -Force | Out-Null
        }

        $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
        Copy-Item ".env" "$backupDir\.env.$timestamp.bak"
        Write-Host "  📦 Created backup: .env.$timestamp.bak" -ForegroundColor Blue
    }

    # Create new .env content
    $envContent = @"
# Wiley Widget Environment Configuration
# Generated by Configuration Lock-In Script
# $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
# DO NOT EDIT MANUALLY - Use configuration lock-in system

# Azure Developer CLI Environment
AZURE_ENV_NAME=dev

# Secrets (resolved from Azure Key Vault)
"@

    foreach ($envVar in $Secrets.Keys) {
        $value = $Secrets[$envVar]
        $envContent += "`n$envVar=$value"
    }

    $envContent += @"

# Azure Resource Configuration
AZURE_KEY_VAULT_NAME=$($CONFIG.VaultName)
AZURE_RESOURCE_GROUP=$($CONFIG.ResourceGroup)

# Configuration Lock Status
CONFIG_LOCKED=true
CONFIG_TIMESTAMP=$(Get-Date -Format "o")
"@

    # Write .env file
    $envContent | Set-Content -Path ".env" -Encoding UTF8 -Force
    Write-Host "  ✅ Updated .env file with resolved secrets" -ForegroundColor Green
}

function Create-LockFile {
    param([hashtable]$Secrets)

    Write-Host "Creating configuration lock file..." -ForegroundColor Yellow

    $lockData = @{
        timestamp = Get-Date -Format "o"
        vaultName = $CONFIG.VaultName
        resourceGroup = $CONFIG.ResourceGroup
        secrets = @{}
        checksums = @{}
    }

    foreach ($envVar in $Secrets.Keys) {
        $value = $Secrets[$envVar]
        $lockData.secrets[$envVar] = @{
            keyVaultName = $CONFIG.Secrets.Keys | Where-Object { $CONFIG.Secrets[$_] -eq $envVar } | Select-Object -First 1
            length = $value.Length
            checksum = (Get-FileHash -InputStream ([System.IO.MemoryStream]::new([System.Text.Encoding]::UTF8.GetBytes($value)))).Hash
        }
    }

    $lockData | ConvertTo-Json -Depth 10 | Set-Content -Path $CONFIG.LockFile -Encoding UTF8
    Write-Host "  ✅ Created lock file: $($CONFIG.LockFile)" -ForegroundColor Green
}

function Verify-Configuration {
    Write-Host "Verifying configuration integrity..." -ForegroundColor Yellow

    $issues = @()

    # Check if .env exists
    if (!(Test-Path ".env")) {
        $issues += "Missing .env file"
    }

    # Check if lock file exists
    if (!(Test-Path $CONFIG.LockFile)) {
        $issues += "Missing configuration lock file"
    }

    # Check environment variables
    foreach ($envVar in $CONFIG.Secrets.Values) {
        $value = [Environment]::GetEnvironmentVariable($envVar, "Process")
        if ([string]::IsNullOrEmpty($value)) {
            $issues += "Missing environment variable: $envVar"
        } elseif ($value.Contains("@Microsoft.KeyVault")) {
            $issues += "Environment variable contains unresolved Key Vault reference: $envVar"
        }
    }

    if ($issues.Count -eq 0) {
        Write-Host "  ✅ Configuration is valid and locked" -ForegroundColor Green
        return $true
    } else {
        Write-Host "  ❌ Configuration issues found:" -ForegroundColor Red
        foreach ($issue in $issues) {
            Write-Host "    - $issue" -ForegroundColor Red
        }
        return $false
    }
}

function Reset-Configuration {
    Write-Host "Resetting configuration..." -ForegroundColor Yellow

    # Remove existing files
    if (Test-Path ".env") { Remove-Item ".env" -Force }
    if (Test-Path $CONFIG.LockFile) { Remove-Item $CONFIG.LockFile -Force }

    # Clear environment variables
    foreach ($envVar in $CONFIG.Secrets.Values) {
        [Environment]::SetEnvironmentVariable($envVar, $null, "Process")
    }

    Write-Host "  ✅ Configuration reset complete" -ForegroundColor Green
}

function Start-Monitoring {
    Write-Host "Starting configuration monitoring..." -ForegroundColor Yellow

    $monitorScript = @"
# Configuration Monitor
# Runs continuously to detect and fix configuration corruption

while (`$true) {
    try {
        # Check if configuration is still valid
        `$envValid = `$true
        `$secrets = @('$($CONFIG.Secrets.Values -join "','")')

        foreach (`$envVar in `$secrets) {
            `$value = [Environment]::GetEnvironmentVariable(`$envVar, "Process")
            if ([string]::IsNullOrEmpty(`$value) -or `$value.Contains("@Microsoft.KeyVault")) {
                `$envValid = `$false
                break
            }
        }

        if (-not `$envValid) {
            Write-Host "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss'): Configuration corrupted - triggering auto-repair" -ForegroundColor Red

            # Auto-repair by running the lock-in script
            & "`$PSScriptRoot\lock-configuration.ps1" -LockIn -Silent
        }

        Start-Sleep -Seconds 30  # Check every 30 seconds
    } catch {
        Write-Host "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss'): Monitor error: `$(`$_.Exception.Message)" -ForegroundColor Red
        Start-Sleep -Seconds 60  # Wait longer on error
    }
}
"@

    $monitorScript | Set-Content -Path "scripts\monitor-configuration.ps1" -Encoding UTF8 -Force
    Write-Host "  ✅ Created monitor script: scripts\monitor-configuration.ps1" -ForegroundColor Green
    Write-Host "  ℹ️  Run '.\scripts\monitor-configuration.ps1' in a separate terminal to start monitoring" -ForegroundColor Blue
}

# Main execution logic
if ($Reset) {
    Reset-Configuration
    exit 0
}

if ($Monitor) {
    Start-Monitoring
    exit 0
}

if ($Verify) {
    $isValid = Verify-Configuration
    exit $(if ($isValid) { 0 } else { 1 })
}

if ($LockIn) {
    Write-Host "🔒 Locking in configuration..." -ForegroundColor Cyan

    # Test Azure connection
    if (!(Test-AzureConnection)) {
        Write-Error "Cannot proceed without Azure authentication"
        exit 1
    }

    # Get secrets from vault
    $secrets = Get-SecretsFromVault
    if ($secrets.Count -eq 0) {
        Write-Error "Failed to retrieve any secrets from Key Vault"
        exit 1
    }

    # Set environment variables
    Set-EnvironmentVariables -Secrets $secrets

    # Update .env file
    Update-EnvFile -Secrets $secrets

    # Create lock file
    Create-LockFile -Secrets $secrets

    # Verify everything worked
    Write-Host "" -ForegroundColor Cyan
    if (Verify-Configuration) {
        Write-Host "🎉 Configuration successfully locked in!" -ForegroundColor Green
        Write-Host "" -ForegroundColor Cyan
        Write-Host "Protection measures activated:" -ForegroundColor White
        Write-Host "✅ Environment variables set in Process scope" -ForegroundColor Green
        Write-Host "✅ .env file updated with resolved secrets" -ForegroundColor Green
        Write-Host "✅ Configuration lock file created" -ForegroundColor Green
        Write-Host "✅ Automatic backups enabled" -ForegroundColor Green
        Write-Host "" -ForegroundColor Cyan
        Write-Host "To monitor for corruption:" -ForegroundColor Yellow
        Write-Host "  .\scripts\lock-configuration.ps1 -Monitor" -ForegroundColor White
        Write-Host "" -ForegroundColor Cyan
        Write-Host "To verify configuration:" -ForegroundColor Yellow
        Write-Host "  .\scripts\lock-configuration.ps1 -Verify" -ForegroundColor White
    } else {
        Write-Error "Configuration lock-in failed verification"
        exit 1
    }
} else {
    Write-Host "Usage:" -ForegroundColor Yellow
    Write-Host "  .\scripts\lock-configuration.ps1 -LockIn    # Lock in current configuration" -ForegroundColor White
    Write-Host "  .\scripts\lock-configuration.ps1 -Verify   # Verify configuration integrity" -ForegroundColor White
    Write-Host "  .\scripts\lock-configuration.ps1 -Reset    # Reset configuration" -ForegroundColor White
    Write-Host "  .\scripts\lock-configuration.ps1 -Monitor  # Start monitoring for corruption" -ForegroundColor White
}

exit 0
