// <auto-generated />
using System.Diagnostics.CodeAnalysis;

// Suppress CA2000 (Dispose objects before losing scope) across test assembly where test framework
// intentionally manages lifetimes or disposal is non-critical for unit tests. Individual tests
// should be audited if resource leaks become a problem.
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "Test code; disposal handled by test framework or intentionally omitted for clarity", Scope = "module")]

// Also suppress analyzer warnings about asserting contains overload guidance in some tests
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "Tests compare literal substrings in exported JSON; StringComparison added where appropriate; remaining occurrences are benign in tests", Scope = "module")]
