// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WileyWidget.Data;

#nullable disable

namespace WileyWidget.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251022200702_AddMunicipalAccountDescriptions")]
    partial class AddMunicipalAccountDescriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WileyWidget.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CacheExpirationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("EnableDataCaching")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableFileLogging")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeChartsInReports")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastReportEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastReportStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastSelectedEnterpriseId")
                        .HasColumnType("int");

                    b.Property<string>("LastSelectedFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastSelectedReportType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QboAccessToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QboClientId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QboClientSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QboRefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("QboTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuickBooksAccessToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuickBooksEnvironment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuickBooksRealmId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuickBooksRefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("QuickBooksTokenExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SelectedLogLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UseDynamicColumns")
                        .HasColumnType("bit");

                    b.Property<double?>("WindowHeight")
                        .HasColumnType("float");

                    b.Property<double?>("WindowLeft")
                        .HasColumnType("float");

                    b.Property<bool?>("WindowMaximized")
                        .HasColumnType("bit");

                    b.Property<double?>("WindowTop")
                        .HasColumnType("float");

                    b.Property<double?>("WindowWidth")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("WileyWidget.Models.AuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Changes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("WileyWidget.Models.BudgetEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ActivityCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("ActualAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BudgetedAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("EncumbranceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndPeriod")
                        .HasColumnType("datetime2");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("int");

                    b.Property<int?>("FundId")
                        .HasColumnType("int");

                    b.Property<int>("FundType")
                        .HasColumnType("int");

                    b.Property<bool>("IsGASBCompliant")
                        .HasColumnType("bit");

                    b.Property<int?>("MunicipalAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("SourceFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SourceRowNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartPeriod")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Variance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityCode");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FundId");

                    b.HasIndex("MunicipalAccountId");

                    b.HasIndex("ParentId");

                    b.HasIndex("SourceRowNumber");

                    b.HasIndex("AccountNumber", "FiscalYear")
                        .IsUnique();

                    b.ToTable("BudgetEntries", t =>
                        {
                            t.HasCheckConstraint("CK_Budget_Positive", "[BudgetedAmount] > 0");
                        });
                });

            modelBuilder.Entity("WileyWidget.Models.BudgetInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("EnterpriseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InteractionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsCost")
                        .HasColumnType("bit");

                    b.Property<decimal>("MonthlyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("PrimaryEnterpriseId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryEnterpriseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.HasIndex("PrimaryEnterpriseId");

                    b.HasIndex("SecondaryEnterpriseId");

                    b.ToTable("BudgetInteraction");
                });

            modelBuilder.Entity("WileyWidget.Models.BudgetPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Year");

                    b.HasIndex("Year", "Status");

                    b.ToTable("BudgetPeriods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "2025 Adopted",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            Year = 2025
                        });
                });

            modelBuilder.Entity("WileyWidget.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentCode")
                        .IsUnique()
                        .HasFilter("[DepartmentCode] IS NOT NULL");

                    b.HasIndex("ParentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("WileyWidget.Models.Enterprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BudgetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CitizenCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MeterReadDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MeterReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MonthlyExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PreviousMeterReadDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PreviousMeterReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Enterprises");
                });

            modelBuilder.Entity("WileyWidget.Models.Entities.Fund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FundCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Funds");
                });

            modelBuilder.Entity("WileyWidget.Models.FiscalYearSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FiscalYearStartDay")
                        .HasColumnType("int");

                    b.Property<int>("FiscalYearStartMonth")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("FiscalYearSettings");
                });

            modelBuilder.Entity("WileyWidget.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("MunicipalAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceDate");

                    b.HasIndex("MunicipalAccountId");

                    b.HasIndex("VendorId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("WileyWidget.Models.MunicipalAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber_Value")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("[AccountNumber]");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BudgetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BudgetPeriodId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("Fund")
                        .HasColumnType("int");

                    b.Property<string>("FundDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentAccountId")
                        .HasColumnType("int");

                    b.Property<string>("QuickBooksId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("TypeDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BudgetPeriodId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ParentAccountId");

                    b.HasIndex("Fund", "Type");

                    b.ToTable("MunicipalAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "CASH IN BANK",
                            RowVersion = new byte[0],
                            Type = 0,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "CASH-BASEBALL FIELD PROJECT",
                            RowVersion = new byte[0],
                            Type = 0,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "INVESTMENTS",
                            RowVersion = new byte[0],
                            Type = 1,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 4,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "INTERGOVERNMENTAL RECEIVABLE",
                            RowVersion = new byte[0],
                            Type = 2,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 5,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "GRANT RECEIVABLE",
                            RowVersion = new byte[0],
                            Type = 2,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 6,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "ACCOUNTS PAYABLE",
                            RowVersion = new byte[0],
                            Type = 6,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 7,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "BASEBALL FIELD PROJECT LOAN",
                            RowVersion = new byte[0],
                            Type = 7,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 8,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "WALKING TRAIL LOAN",
                            RowVersion = new byte[0],
                            Type = 7,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 9,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "DUE TO/FROM TOW GENERAL FUND",
                            RowVersion = new byte[0],
                            Type = 8,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 10,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "DUE TO/FROM TOW UTILITY FUND",
                            RowVersion = new byte[0],
                            Type = 8,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 11,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "FUND BALANCE",
                            RowVersion = new byte[0],
                            Type = 10,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 12,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "Opening Bal Equity",
                            RowVersion = new byte[0],
                            Type = 9,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 13,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "Retained Earnings",
                            RowVersion = new byte[0],
                            Type = 9,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 14,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "STATE APPORTIONMENT",
                            RowVersion = new byte[0],
                            Type = 16,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 15,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "WALKING TRAIL DONATION",
                            RowVersion = new byte[0],
                            Type = 13,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 16,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "BASEBALL FIELD DONATIONS",
                            RowVersion = new byte[0],
                            Type = 13,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 17,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "GRANT REVENUES",
                            RowVersion = new byte[0],
                            Type = 13,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 18,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "MISC REVENUE",
                            RowVersion = new byte[0],
                            Type = 16,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 19,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "WALKING TRAIL REVENUE",
                            RowVersion = new byte[0],
                            Type = 16,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 20,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "INTEREST ON INVESTMENTS",
                            RowVersion = new byte[0],
                            Type = 14,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 21,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "TRANSFER FROM REC FUND",
                            RowVersion = new byte[0],
                            Type = 30,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 22,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "BALLFIELD ACCRUED INTEREST",
                            RowVersion = new byte[0],
                            Type = 24,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 23,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "WALKING TRAIL ACCRUED INTEREST",
                            RowVersion = new byte[0],
                            Type = 24,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 24,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "CAPITAL IMP - BALL COMPLEX",
                            RowVersion = new byte[0],
                            Type = 29,
                            TypeDescription = "Asset"
                        },
                        new
                        {
                            Id = 25,
                            Balance = 0m,
                            BudgetAmount = 0m,
                            BudgetPeriodId = 1,
                            DepartmentId = 1,
                            Fund = 8,
                            FundDescription = "General Fund",
                            IsActive = true,
                            Name = "PARKS - DEVELOPMENT",
                            RowVersion = new byte[0],
                            Type = 29,
                            TypeDescription = "Asset"
                        });
                });

            modelBuilder.Entity("WileyWidget.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BudgetEntryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MunicipalAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BudgetEntryId");

                    b.HasIndex("MunicipalAccountId");

                    b.HasIndex("TransactionDate");

                    b.ToTable("Transactions", t =>
                        {
                            t.HasCheckConstraint("CK_Transaction_NonZero", "[Amount] != 0");
                        });
                });

            modelBuilder.Entity("WileyWidget.Models.UtilityCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AccountCloseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("AccountOpenDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BusinessLicenseNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ConnectDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DisconnectDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("LastPaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MailingAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MailingCity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MailingState")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("MailingZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MeterNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ServiceAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ServiceCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ServiceLocation")
                        .HasColumnType("int");

                    b.Property<string>("ServiceState")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("ServiceZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("UtilityCustomers");
                });

            modelBuilder.Entity("WileyWidget.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("Vendor", (string)null);
                });

            modelBuilder.Entity("WileyWidget.Models.BudgetEntry", b =>
                {
                    b.HasOne("WileyWidget.Models.Department", "Department")
                        .WithMany("BudgetEntries")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WileyWidget.Models.Entities.Fund", "Fund")
                        .WithMany("BudgetEntries")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WileyWidget.Models.MunicipalAccount", null)
                        .WithMany("BudgetEntries")
                        .HasForeignKey("MunicipalAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WileyWidget.Models.BudgetEntry", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Fund");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("WileyWidget.Models.BudgetInteraction", b =>
                {
                    b.HasOne("WileyWidget.Models.Enterprise", null)
                        .WithMany("BudgetInteractions")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WileyWidget.Models.Enterprise", "PrimaryEnterprise")
                        .WithMany()
                        .HasForeignKey("PrimaryEnterpriseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WileyWidget.Models.Enterprise", "SecondaryEnterprise")
                        .WithMany()
                        .HasForeignKey("SecondaryEnterpriseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PrimaryEnterprise");

                    b.Navigation("SecondaryEnterprise");
                });

            modelBuilder.Entity("WileyWidget.Models.Department", b =>
                {
                    b.HasOne("WileyWidget.Models.Department", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("WileyWidget.Models.Invoice", b =>
                {
                    b.HasOne("WileyWidget.Models.MunicipalAccount", "MunicipalAccount")
                        .WithMany("Invoices")
                        .HasForeignKey("MunicipalAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WileyWidget.Models.Vendor", "Vendor")
                        .WithMany("Invoices")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MunicipalAccount");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("WileyWidget.Models.MunicipalAccount", b =>
                {
                    b.HasOne("WileyWidget.Models.BudgetPeriod", "BudgetPeriod")
                        .WithMany("Accounts")
                        .HasForeignKey("BudgetPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WileyWidget.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WileyWidget.Models.MunicipalAccount", "ParentAccount")
                        .WithMany("ChildAccounts")
                        .HasForeignKey("ParentAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("WileyWidget.Models.AccountNumber", "AccountNumber", b1 =>
                        {
                            b1.Property<int>("MunicipalAccountId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("AccountNumber");

                            b1.HasKey("MunicipalAccountId");

                            b1.ToTable("MunicipalAccounts");

                            b1.WithOwner()
                                .HasForeignKey("MunicipalAccountId");

                            b1.HasData(
                                new
                                {
                                    MunicipalAccountId = 1,
                                    Value = "110"
                                },
                                new
                                {
                                    MunicipalAccountId = 2,
                                    Value = "110.1"
                                },
                                new
                                {
                                    MunicipalAccountId = 3,
                                    Value = "120"
                                },
                                new
                                {
                                    MunicipalAccountId = 4,
                                    Value = "130"
                                },
                                new
                                {
                                    MunicipalAccountId = 5,
                                    Value = "140"
                                },
                                new
                                {
                                    MunicipalAccountId = 6,
                                    Value = "210"
                                },
                                new
                                {
                                    MunicipalAccountId = 7,
                                    Value = "211"
                                },
                                new
                                {
                                    MunicipalAccountId = 8,
                                    Value = "212"
                                },
                                new
                                {
                                    MunicipalAccountId = 9,
                                    Value = "230"
                                },
                                new
                                {
                                    MunicipalAccountId = 10,
                                    Value = "240"
                                },
                                new
                                {
                                    MunicipalAccountId = 11,
                                    Value = "290"
                                },
                                new
                                {
                                    MunicipalAccountId = 12,
                                    Value = "3000"
                                },
                                new
                                {
                                    MunicipalAccountId = 13,
                                    Value = "33000"
                                },
                                new
                                {
                                    MunicipalAccountId = 14,
                                    Value = "310"
                                },
                                new
                                {
                                    MunicipalAccountId = 15,
                                    Value = "314"
                                },
                                new
                                {
                                    MunicipalAccountId = 16,
                                    Value = "315"
                                },
                                new
                                {
                                    MunicipalAccountId = 17,
                                    Value = "320"
                                },
                                new
                                {
                                    MunicipalAccountId = 18,
                                    Value = "323"
                                },
                                new
                                {
                                    MunicipalAccountId = 19,
                                    Value = "325"
                                },
                                new
                                {
                                    MunicipalAccountId = 20,
                                    Value = "360"
                                },
                                new
                                {
                                    MunicipalAccountId = 21,
                                    Value = "370"
                                },
                                new
                                {
                                    MunicipalAccountId = 22,
                                    Value = "2111"
                                },
                                new
                                {
                                    MunicipalAccountId = 23,
                                    Value = "2112"
                                },
                                new
                                {
                                    MunicipalAccountId = 24,
                                    Value = "410"
                                },
                                new
                                {
                                    MunicipalAccountId = 25,
                                    Value = "420"
                                });
                        });

                    b.Navigation("AccountNumber")
                        .IsRequired();

                    b.Navigation("BudgetPeriod");

                    b.Navigation("Department");

                    b.Navigation("ParentAccount");
                });

            modelBuilder.Entity("WileyWidget.Models.Transaction", b =>
                {
                    b.HasOne("WileyWidget.Models.BudgetEntry", "BudgetEntry")
                        .WithMany("Transactions")
                        .HasForeignKey("BudgetEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WileyWidget.Models.MunicipalAccount", null)
                        .WithMany("Transactions")
                        .HasForeignKey("MunicipalAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BudgetEntry");
                });

            modelBuilder.Entity("WileyWidget.Models.BudgetEntry", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("WileyWidget.Models.BudgetPeriod", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("WileyWidget.Models.Department", b =>
                {
                    b.Navigation("BudgetEntries");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("WileyWidget.Models.Enterprise", b =>
                {
                    b.Navigation("BudgetInteractions");
                });

            modelBuilder.Entity("WileyWidget.Models.Entities.Fund", b =>
                {
                    b.Navigation("BudgetEntries");
                });

            modelBuilder.Entity("WileyWidget.Models.MunicipalAccount", b =>
                {
                    b.Navigation("BudgetEntries");

                    b.Navigation("ChildAccounts");

                    b.Navigation("Invoices");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("WileyWidget.Models.Vendor", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
