-- Auto-generated from OCR PDF chart of accounts
-- Source: 1691_251009113607_001 OCR.pdf
SET NOCOUNT ON;

DECLARE @ActiveBudgetPeriodId INT = (
    SELECT TOP (1) Id
    FROM BudgetPeriods
    WHERE IsActive = 1
    ORDER BY [Year] DESC, Id DESC
);

IF @ActiveBudgetPeriodId IS NULL
BEGIN
    SET @ActiveBudgetPeriodId = 1;
END;

DECLARE @Coa TABLE (
    AccountNumber NVARCHAR(20) NOT NULL,
    [Name] NVARCHAR(100) NOT NULL,
    [Type] INT NOT NULL,
    TypeDescription NVARCHAR(50) NOT NULL
);

INSERT INTO @Coa (AccountNumber, [Name], [Type], TypeDescription)
VALUES
    (N'110', N'CASH IN BANK', 0, N'Cash'),
    (N'110.1', N'CASH-BASEBALL FIELD PROJECT', 0, N'Cash'),
    (N'120', N'INVESTMENTS', 0, N'Cash'),
    (N'130', N'INTERGOVERNMENTAL RECEIVABLE', 0, N'Cash'),
    (N'140', N'GRANT RECEIVABLE', 0, N'Cash'),
    (N'210', N'ACCOUNTS PAYABLE', 6, N'Payables'),
    (N'290', N'BASEBALL FIELF PROJECT LOAN . WALKING TRAIL LOAN . DUE TO/FROM TOW GENERAL FUND . DUE TO/FROM TOW UTILITY FUND . FUND BALANCE', 6, N'Payables'),
    (N'30000', N'Opening Bal', 10, N'FundBalance'),
    (N'32000', N'Unrestricted Net Assets', 10, N'FundBalance'),
    (N'370', N'GAIN/LOSS DISPOSAL OF ASSETS', 16, N'Revenue'),
    (N'360', N'TRANSFER FROM REC FUND', 16, N'Revenue'),
    (N'211.1', N'BALLFIELD ACCRUED INTEREST', 6, N'Payables'),
    (N'212.2', N'WALKING TRAIL ACCRUED INTEREST', 6, N'Payables'),
    (N'1120', N'CASH IN BANK - BASEBALL/SOFTBAL', 0, N'Cash'),
    (N'1130', N'SAVINGS ACCOUNT', 0, N'Cash'),
    (N'1840', N'BUILDINGS', 0, N'Cash'),
    (N'1860', N'EQUIPMENT', 0, N'Cash'),
    (N'1900', N'ACCUMULATED DEPRICIATION', 0, N'Cash'),
    (N'271', N'Retained Earnings', 10, N'FundBalance'),
    (N'4110.2', N'VOLLEYBALL DUES', 16, N'Revenue'),
    (N'01', N'CHECKING ACCOUNT-Enterprise', 0, N'Cash'),
    (N'02', N'WSD-General Fund', 0, N'Cash'),
    (N'51.3', N'LEGACY BANK CD #6469', 0, N'Cash'),
    (N'2000', N'Undeposited Funds', 0, N'Cash'),
    (N'80', N'CONSTRUCTION IN PROGRESS', 0, N'Cash'),
    (N'05', N'ACCOUNTS RECEIVABLE', 0, N'Cash'),
    (N'15.7', N'INTERGOVERNMENTAL RECEIVABLE', 0, N'Cash'),
    (N'32', N'CASH WITH COUNTY TREASURER', 0, N'Cash'),
    (N'40', N'LAND', 0, N'Cash'),
    (N'41', N'SEWER SYSTEM', 0, N'Cash'),
    (N'42', N'EQUIPMENT', 0, N'Cash'),
    (N'43', N'FURNITURE & FIXTURES', 0, N'Cash'),
    (N'46', N'ACCUMULATED DEPRECIATION', 0, N'Cash'),
    (N'55', N'PREPAID INSURANCE', 0, N'Cash'),
    (N'205', N'DEFERRED REVENUE - PROPERTY TAX', 6, N'Payables'),
    (N'215', N'DEFERRED REVENUE-RESCUE FUND', 6, N'Payables'),
    (N'217.1', N'FEDERAL W/H TAXES PAYBALE', 6, N'Payables'),
    (N'217.2', N'STATE W/H TAXES PAYABLE', 6, N'Payables'),
    (N'217.3', N'SOC SEC W/H TAXES PAYABLE', 6, N'Payables'),
    (N'222', N'DUE TO/FROM SANITATION DISTRICT', 6, N'Payables'),
    (N'301', N'SEWAGE SALES', 16, N'Revenue'),
    (N'302', N'TAP FEES', 16, N'Revenue'),
    (N'310', N'GENERAL PROPERTY TAXES', 16, N'Revenue'),
    (N'310.1', N'DELINQUENT GEN. PROPERTY TAXES', 16, N'Revenue'),
    (N'311', N'S.0. TAXES', 16, N'Revenue'),
    (N'312', N'TAXA', 16, N'Revenue'),
    (N'313', N'SENIOR HOMESTEAD EXEMPTION', 16, N'Revenue'),
    (N'315', N'INTEREST ON INVESTMENTS Income', 16, N'Revenue'),
    (N'320', N'PENALTIES & INTEREST ON TAXES', 16, N'Revenue'),
    (N'320.1', N'REFUND TAX OVERPAYMENT', 16, N'Revenue'),
    (N'321', N'MISCELLANEOUS', 16, N'Revenue'),
    (N'322', N'WSD POND PROJECT GRANTS', 16, N'Revenue'),
    (N'323', N'WSD-AMER RESCUE FUND-PONDS PROJ', 16, N'Revenue'),
    (N'492', N'MILAGE REIMBURSMENT', 24, N'Expense'),
    (N'210.1', N'CD LOAN INTEREST', 6, N'Payables'),
    (N'401', N'PERMITS & ASSESSMENTS', 24, N'Expense'),
    (N'401.1', N'BANK SERVICE & INTEREST CHARGE', 24, N'Expense'),
    (N'401.2', N'INTEREST EXPENSE-TRASH TRUCK', 24, N'Expense'),
    (N'405', N'OUTSIDE SERVICE - LAB FEES', 24, N'Expense'),
    (N'405.1', N'BUDGET, AUDIT, LEGAL', 24, N'Expense'),
    (N'410', N'OFFICE SUPPLIES/POSTAGE', 24, N'Expense'),
    (N'413.4', N'EDUCATION', 24, N'Expense'),
    (N'415', N'CAPITAL OUTLAY', 24, N'Expense'),
    (N'416', N'DUES & SUBSCRIPTIONS', 24, N'Expense'),
    (N'418', N'SERVICE CONTRACT/WARRANTY', 24, N'Expense'),
    (N'420', N'COLLECTION FEE', 24, N'Expense'),
    (N'425', N'SUPPLIES & EXPENSES', 24, N'Expense'),
    (N'430', N'GIFTS/APPRECIATION', 24, N'Expense'),
    (N'432.53', N'SEWER CLEANING', 24, N'Expense'),
    (N'433.51', N'SALARIES', 24, N'Expense'),
    (N'435', N'LAGOON CLEANING', 24, N'Expense'),
    (N'440', N'DEPRECIATION', 24, N'Expense'),
    (N'445', N'COUNTY TREASURER FEES', 24, N'Expense'),
    (N'483', N'PAYROLL TAXES - FICA/UNEMPLOYMT', 24, N'Expense'),
    (N'484', N'WATER PROJECT EXPENSES', 24, N'Expense'),
    (N'485', N'ENGINEERING', 24, N'Expense'),
    (N'486', N'TRANSFER TO CAPITAL PROJECTS', 24, N'Expense'),
    (N'487', N'INTEREST - RURAL DEVELOP. LOAN', 24, N'Expense'),
    (N'489', N'PICKUP USAGE FEE', 24, N'Expense'),
    (N'490', N'TRASFER TO UTILITY FUNDS', 24, N'Expense'),
    (N'491', N'TRANSFER TO CC FUND', 24, N'Expense'),
    (N'493', N'TRANSFER TO OTHER FUNDS', 24, N'Expense'),
    (N'101', N'CASH IN VRSI GRANT CHKG ACCT/TF', 0, N'Cash'),
    (N'101.1', N'CASH IN OPER. CHKG ACCT/HILDA', 0, N'Cash'),
    (N'105', N'CERTIFICATE OF DEPOSIT #5002', 0, N'Cash'),
    (N'106', N'CERTIFICATE OF DEPOSIT #5001', 0, N'Cash'),
    (N'107', N'CERTIFICATE OF DEPOSIT #5288', 0, N'Cash'),
    (N'108', N'CERTIFICATE OF DEPOSIT #5745', 0, N'Cash'),
    (N'202', N'ACCOUNTS PAYABLE - VRSI GRANT', 6, N'Payables'),
    (N'202.1', N'ACCOUNTS PAYABLE - OPERATE ACCT', 6, N'Payables'),
    (N'206', N'DEFERRED REV SIDEWALK TRAIL', 6, N'Payables'),
    (N'223', N'DUE TO/FROM CC OPERATING ACCT', 6, N'Payables'),
    (N'319.1', N'MISCELLANEOUS INCOME Income', 16, N'Revenue'),
    (N'330', N'INTERGOVERNMENTAL REV-PRWS CNTY', 16, N'Revenue'),
    (N'334', N'SEVERENCE TAX', 16, N'Revenue'),
    (N'334.1', N'HRSA GRANT', 16, N'Revenue'),
    (N'334.2', N'COLO RURAL HEALTH GRANT', 16, N'Revenue'),
    (N'361', N'INTEREST ON INVESTMENTS', 16, N'Revenue'),
    (N'364', N'INSURANCE PROCEEDS Income', 16, N'Revenue'),
    (N'364.1', N'LEASE PAYMENTS PRINCIPAL', 16, N'Revenue'),
    (N'367', N'DONATIONS', 16, N'Revenue'),
    (N'367.5', N'TRANSFER FROM TOW GENERAL', 16, N'Revenue'),
    (N'368', N'MISCELLANEOUS', 16, N'Revenue'),
    (N'369', N'VAN RENTAL', 16, N'Revenue'),
    (N'155', N'PREPAID', 24, N'Expense'),
    (N'402', N'BANK SERVICE CHARGES/PENALTIES', 24, N'Expense'),
    (N'3.2', N'ACTIVITY DIRECTOR SALARY', 0, N'Cash'),
    (N'3.3', N'PAYROLL TAXES - FICA & UNEMP', 0, N'Cash'),
    (N'3.4', N'EDUCATION/TRAVEL', 0, N'Cash'),
    (N'4.1', N'UTILITIES', 0, N'Cash'),
    (N'5.17', N'OFFICE SUPPLIES/EQUIPMENT', 0, N'Cash'),
    (N'5.2', N'LEGAL EXPENSE - ATTORNEY', 24, N'Expense'),
    (N'5.21', N'ADMINISTRATIVE EXPENSES', 0, N'Cash'),
    (N'415.53', N'INSURANCE - BLDG/PROP/LIAB', 24, N'Expense'),
    (N'415.54', N'INSURANCE - VAN', 24, N'Expense'),
    (N'417', N'COUNTY TREASURER FEES', 24, N'Expense'),
    (N'419.41', N'JANITORIAL SERVICE SALARY', 24, N'Expense'),
    (N'419.42', N'BUILDING MAINT/SUPPLIES', 24, N'Expense'),
    (N'441', N'SUMMER READING SUPPLIES/EQUIP', 24, N'Expense'),
    (N'461', N'Advertising and Promotion', 24, N'Expense'),
    (N'66900', N'Reconciliation Discrepancies', 24, N'Expense'),
    (N'141', N'BUILDINGS', 0, N'Cash'),
    (N'142', N'EQUIPMENT', 0, N'Cash'),
    (N'146', N'ACCUMULATED DEPRECIATION', 0, N'Cash'),
    (N'101.5', N'REPAIRS ACCOUNT Other', 0, N'Cash'),
    (N'143', N'IMPROVEMENTS Other', 0, N'Cash'),
    (N'241', N'SECURITY DEPOSITS', 6, N'Payables'),
    (N'211', N'PERM. LOAN SBW', 6, N'Payables'),
    (N'212', N'LOAN ACCOUNT-12141', 6, N'Payables'),
    (N'362', N'RENT RECEIPTS Income', 16, N'Revenue'),
    (N'363', N'GAIN/LOSS ON DISPOSAL OF A Income', 16, N'Revenue'),
    (N'400', N'BAD DEBT EXPENSE', 24, N'Expense'),
    (N'415.175', N'COUNTY TAX ASSMT', 24, N'Expense'),
    (N'415.210', N'ADMINISTRATIVE EXPENSE', 24, N'Expense'),
    (N'415.220', N'BANK SERVICE CHARGES', 24, N'Expense'),
    (N'419.420', N'DO NOT USE/PRIOR MAINT', 24, N'Expense'),
    (N'419.5', N'BLDGS & GROUNDS - UTILITIES', 24, N'Expense'),
    (N'419.6', N'COMMUNITY CENTER UTILITIES', 24, N'Expense'),
    (N'471.2', N'PERM LOAN- SBW', 24, N'Expense'),
    (N'472.2', N'LOAN INTEREST', 24, N'Expense'),
    (N'480', N'INSURANCE - PROPERTY/AUTO/LIAB', 24, N'Expense'),
    (N'482', N'Equipment Rental', 24, N'Expense'),
    (N'485.2', N'Miscellaneous Expense', 24, N'Expense'),
    (N'485.3', N'Postage and Delivery', 24, N'Expense'),
    (N'102', N'PETTY CASH', 0, N'Cash'),
    (N'103.2', N'KEY PUMP DEPOSIT (WG & O)', 0, N'Cash'),
    (N'103.3', N'PO BOX KEY DEPOSIT Other', 0, N'Cash'),
    (N'1000', N'*Accounts Receivable', 0, N'Cash'),
    (N'15.4', N'ACCOUNTS RECEIVABLE - MISC', 0, N'Cash'),
    (N'15.41', N'ACCOUNTS RECEIVABLE - SIDEWALK', 0, N'Cash'),
    (N'15.5', N'INSURANCE - PROPERTY/BLDG/AUTO', 0, N'Cash'),
    (N'15.71', N'ACCOUNTS RECEIVABLE - COUNT R&B', 0, N'Cash'),
    (N'15.72', N'HOUSING AUTHORITY RECEIVABLE', 0, N'Cash'),
    (N'16', N'ALLOWANCE FOR DOUBTFUL ACCOUNT Other', 0, N'Cash'),
    (N'12100', N'Inventory', 0, N'Cash'),
    (N'132', N'CASH WITH COUNTY TREASURER', 0, N'Cash'),
    (N'50', N'SIDEWALK AND TRAIL PROJECT', 0, N'Cash'),
    (N'51', N'INVESTMENTS CEBT CD#0221375820', 0, N'Cash'),
    (N'52', N'TOWN OF WILEY - UTL RD RESERVE', 0, N'Cash'),
    (N'53', N'PREPAID', 24, N'Expense'),
    (N'155.1', N'PREPAID DUES & SUBSCRIPTIONS', 0, N'Cash'),
    (N'156', N'Wiley Hay Days', 0, N'Cash'),
    (N'160', N'HAROLD SMITH PARK CHECKING', 0, N'Cash'),
    (N'202.2', N'CC CITY OF LAMAR ELEC - PAYABLE', 6, N'Payables'),
    (N'203', N'ACCRUED PAYROLL', 6, N'Payables'),
    (N'205.10', N'DEFERRED REVENUE - FLOOD GRANT', 6, N'Payables'),
    (N'205.20', N'DEFERRED REVENUE - RENTS', 6, N'Payables'),
    (N'206.5', N'DEFERRED REVENUE ARP', 6, N'Payables'),
    (N'2110', N'Direct Deposit Liabilities', 6, N'Payables'),
    (N'2120', N'Payroll', 0, N'Cash'),
    (N'216', N'PAYROLL CLEARING', 6, N'Payables'),
    (N'217.4', N'PAYROLL w/h - GARNISHMENT', 6, N'Payables'),
    (N'217.5', N'STATE UNEMP TAX PAYABLE', 6, N'Payables'),
    (N'217.6', N'FEDERAL UNEMP TAX PAYABLE', 6, N'Payables'),
    (N'217.7', N'FAMLI TAX PAYABLE', 6, N'Payables'),
    (N'217.8', N'SIMPLE IRA PAYABLE', 6, N'Payables'),
    (N'221', N'DUE TO/FROM CONSERVATION TRUST', 6, N'Payables'),
    (N'222.5', N'DUE TO FROM WSD-GENERAL', 6, N'Payables'),
    (N'223.2', N'DUE TO/FROM BROOKSIDE', 6, N'Payables'),
    (N'223.5', N'DUE TO/FROM CC#2 FUND', 6, N'Payables'),
    (N'224', N'DUE TO/FROM WILEY HAY DAY', 6, N'Payables'),
    (N'225', N'DUE TO/FROM UTILITY FUND', 6, N'Payables'),
    (N'226', N'REVOLVING LOAN-SIDEWALK TRAIL', 6, N'Payables'),
    (N'24000', N'Payroll Liabilities', 6, N'Payables'),
    (N'10.5', N'RECYCLING (INCOME)', 0, N'Cash'),
    (N'1.1', N'ACCRUED INTEREST (PARK DRY WELL', 0, N'Cash'),
    (N'1.2', N'SENIOR HOMESTEAD EXEMPTION', 0, N'Cash'),
    (N'318.1', N'OCCUPATIONAL TAX - PTI', 16, N'Revenue'),
    (N'318.2', N'FRANCHISE FEE', 16, N'Revenue'),
    (N'319', N'PENALTIES & INTEREST ON TAXES', 16, N'Revenue'),
    (N'321.1', N'LIQUOR LICENSES', 16, N'Revenue'),
    (N'321.7', N'PERMIT - FIREWORKS', 16, N'Revenue'),
    (N'322.5', N'PET CLINIC - DON''T USE', 16, N'Revenue'),
    (N'322.7', N'DOG LICENSES', 16, N'Revenue'),
    (N'324', N'WEED CONTROL', 16, N'Revenue'),
    (N'332.100', N'MINERAL LEASE', 16, N'Revenue'),
    (N'333', N'CIGARETTE TAX', 16, N'Revenue'),
    (N'334.31', N'HIGHWAY USERS TAX', 16, N'Revenue'),
    (N'335', N'COVID RELIEF FUNDS', 16, N'Revenue'),
    (N'336', N'SALES TAX REVENUE', 16, N'Revenue'),
    (N'337.17', N'COUNTY ROAD & BRIDGE', 16, N'Revenue'),
    (N'340', N'Harold Smith Park GRANT', 16, N'Revenue'),
    (N'341.4', N'COPIES/FAX REVENUE', 16, N'Revenue'),
    (N'350', N'WILEY HAY DAYS DONATIONS', 16, N'Revenue'),
    (N'355', N'GOCO GRANT-MASTER PLAN', 16, N'Revenue'),
    (N'362.5', N'WALKING TRAIL DONATIONS', 16, N'Revenue'),
    (N'362.6', N'ESGAR FOUNDAION/PARK EQUIP', 16, N'Revenue'),
    (N'365', N'DIVIDENDS', 16, N'Revenue'),
    (N'372.1', N'TRANSFER FROM OTHER FUNDS', 16, N'Revenue'),
    (N'372.2', N'TRANSFER FROM UTILITY FUND', 16, N'Revenue'),
    (N'372.3', N'BCL GROUND MAINTENANCE', 16, N'Revenue'),
    (N'373', N'PICKUP USAGE FEE', 16, N'Revenue'),
    (N'374', N'CODE ENFORCEMENT FINES', 16, N'Revenue'),
    (N'375', N'CAPITAL OUTLAY-PARK GRANT', 16, N'Revenue'),
    (N'412', N'SIDEWALK TRAIL EXPENSES', 24, N'Expense'),
    (N'412.5', N'Brookside Drive Development', 24, N'Expense'),
    (N'413.1', N'MAYOR', 24, N'Expense'),
    (N'413.2', N'ADMIN - CLERK SALARY', 24, N'Expense'),
    (N'413.21', N'ADMIN - DEPUTY CLERK SALARY', 24, N'Expense'),
    (N'413.22', N'ADMIN - CODE ENFORCEMENT', 24, N'Expense'),
    (N'413.3', N'PAYROLL TAXES - FICA', 24, N'Expense'),
    (N'3.5', N'TRAVEL & TRANSPORTATION', 0, N'Cash'),
    (N'3.6', N'PAYROLL TAXES - UNEMP INS', 0, N'Cash'),
    (N'3.7', N'FAMLI', 0, N'Cash'),
    (N'3.8', N'SIMPLE IRA-COMPANY', 0, N'Cash'),
    (N'5.11', N'AUDIT & BUDGET', 24, N'Expense'),
    (N'5.12', N'PROFESSIONAL SERVICES', 0, N'Cash'),
    (N'5.175', N'COUNTY TAX ASSESSMENT', 0, N'Cash'),
    (N'5.18', N'POSTAGE', 0, N'Cash'),
    (N'5.19', N', OFFICE EQUIPMENT', 0, N'Cash'),
    (N'5.51', N'INSURANCE - PUB LIAB/LIAB/UMBRL', 0, N'Cash'),
    (N'415.52', N'INSURANCE - WORKER''S COMP', 24, N'Expense'),
    (N'415.75', N'PET CLINIC', 24, N'Expense'),
    (N'415.76', N'RECYCLING (EXPENSE)', 24, N'Expense'),
    (N'416.2', N'PREPAID EXPENSE', 24, N'Expense'),
    (N'419.43', N'GARAGE IMPROVEMENTS', 24, N'Expense'),
    (N'419.44', N', BUILDING SUPPLIES/MAINTENANCE', 24, N'Expense'),
    (N'419.7', N'COMMUNITY CENTER SALARY', 24, N'Expense'),
    (N'431', N'STREETS - MAINT/SUPPLIES', 24, N'Expense'),
    (N'431.1', N'STREETS - SNOW & ICE REMOVAL', 24, N'Expense'),
    (N'431.4', N'STREETS - SALARY', 24, N'Expense'),
    (N'431.41', N'STREET SALARIES - PART TIME', 24, N'Expense'),
    (N'431.5', N'STREETS 0 GRAVEL', 24, N'Expense'),
    (N'431.6', N'STREETS -SEAL COATING/SURFACING', 24, N'Expense'),
    (N'431.61', N'STREET SIGNS', 24, N'Expense'),
    (N'431.7', N'STREETS/REPLACING', 24, N'Expense'),
    (N'432.2', N'STREETS EQUIP - REPAIR/MAINT', 24, N'Expense'),
    (N'432.3', N'STREET LIGHTING', 24, N'Expense'),
    (N'432.4', N'STREET EQUIP - FUEL', 24, N'Expense'),
    (N'432.51', N'STREETS - EQUIPMENT', 24, N'Expense'),
    (N'433', N'SHOP SUPPLIES/EQUIPMENT', 24, N'Expense'),
    (N'433.1', N'CC - CAP OUTLAY - LAMAR ELEC', 24, N'Expense'),
    (N'433.2', N'CAPITOL PROJECT', 24, N'Expense'),
    (N'433.3', N'PUBLIC SAFETY', 24, N'Expense'),
    (N'451.1', N'PARK - SALARY', 24, N'Expense'),
    (N'451.2', N'PARK - PART TIME SALARY', 24, N'Expense'),
    (N'452', N'PARK - SUPPLIES/REPAIRS', 24, N'Expense'),
    (N'452.1', N'PARK - UTILITIES', 24, N'Expense'),
    (N'453', N'TRASH SUPPLIES/REPAIRS', 24, N'Expense'),
    (N'454', N'TRASH DISPOSAL-TRASH SERVICE', 24, N'Expense'),
    (N'455', N'ELECTIONS - SUPPLIES', 24, N'Expense'),
    (N'456', N'MISQUITO SPRAYING', 24, N'Expense'),
    (N'459', N'FIRE DISTRICT PAYMENT', 24, N'Expense'),
    (N'460.1', N'ADMIN-CLERK SALARIES', 24, N'Expense'),
    (N'462', N'INT/PENALTIES W/H TAXES', 24, N'Expense'),
    (N'465', N'CHRISTMAS LIGHTING CONTEST', 24, N'Expense'),
    (N'481', N'FEMA', 24, N'Expense'),
    (N'485.4', N'MEALS', 24, N'Expense'),
    (N'495', N'CAPITAL OUTLAY', 24, N'Expense'),
    (N'49900', N'Uncategorized Income', 16, N'Revenue'),
    (N'18', N'GRANT RECEIVABLE Other', 0, N'Cash'),
    (N'21', N'ACCOUNTS RECEIVABLE - WSD', 0, N'Cash'),
    (N'2100', N'Inventory', 0, N'Cash'),
    (N'43.5', N'PREPAID EXPENSES', 0, N'Cash'),
    (N'51.1', N'INVESTMENTS - C D', 0, N'Cash'),
    (N'51.2', N'INVESTMENTS - CD #1358', 0, N'Cash'),
    (N'61', N'FIXED ASSETS', 0, N'Cash'),
    (N'61.5', N'REPLACEMENT WELL', 0, N'Cash'),
    (N'61.6', N'WALKER WELL WATER PROJECT', 0, N'Cash'),
    (N'62.0', N'TRASH TRUCK', 0, N'Cash'),
    (N'69', N'ACCUMULATED DEPRECIATION', 0, N'Cash'),
    (N'0.1', N'PROFESSIONAL SERVICES', 0, N'Cash'),
    (N'1.3', N'WALKER WELL LOAN (USDA RD)', 0, N'Cash'),
    (N'1.4', N'RVS SOFTWARE - PRINTER', 0, N'Cash'),
    (N'1.5', N'RVS SOFTWARE - SOFTWARE PROGRAM', 0, N'Cash'),
    (N'1.6', N'TRASH TRUCK, AND DUMPSTRS', 0, N'Cash'),
    (N'10', N'Direct Deposit Liabilities', 0, N'Cash'),
    (N'7.1', N'FEDERAL w/h PAYABLE', 0, N'Cash'),
    (N'7.2', N'STATE w/h PAYABLE', 0, N'Cash'),
    (N'7.3', N'SOC SEC w/h PAYABLE', 0, N'Cash'),
    (N'264', N'CONTRIBUTED CAPITAL', 6, N'Payables'),
    (N'270', N'DUE TO/FROM GENERAL FUND', 6, N'Payables'),
    (N'270.1', N'DUE TO/FROM CONSERVATION TRUST', 6, N'Payables'),
    (N'270.2', N'DUE TO/FROM BROOKSIDE', 6, N'Payables'),
    (N'271.0', N'FUND BALANCE', 6, N'Payables'),
    (N'272', N'RETAINED EARNINGS', 6, N'Payables'),
    (N'273', N'DEFERRED GRANT REVENUE', 6, N'Payables'),
    (N'319.2', N'DOLA GRANT - WATER PROJECT', 16, N'Revenue'),
    (N'319.3', N'USDA RD GRANT - WATER PROJECT', 16, N'Revenue'),
    (N'319.4', N'WATER TANK REPLACEMENT PROJECT', 16, N'Revenue'),
    (N'319.5', N'USDA BACKHOE GRANT', 16, N'Revenue'),
    (N'348', N'TRASH SALES', 16, N'Revenue'),
    (N'366', N'BCL MANAGEMENT FEE', 16, N'Revenue'),
    (N'392', N'GAIN/LOSS DISPOSAL OF ASSETS', 16, N'Revenue'),
    (N'393', N'SALE OF SUPPLIES', 16, N'Revenue'),
    (N'401.3', N'DEPRECIATION EXPENSE-TRASH TRUC', 24, N'Expense'),
    (N'9.4', N'FUEL', 24, N'Expense'),
    (N'442', N'BUILDING MAINTENANCE', 24, N'Expense'),
    (N'455.10', N'SALARIES-TRASH', 24, N'Expense'),
    (N'455.11', N'LEASE PAYMENT-TRASH TRUCK', 24, N'Expense'),
    (N'460', N'SUPT SALARIES', 24, N'Expense'),
    (N'460.12', N'ADMIN-WATER PT SALARIES', 24, N'Expense'),
    (N'460.2', N'ADMIN - DEPUTY CLERK SALARIES', 24, N'Expense'),
    (N'467', N'OTHER ADMINISTRATIVE EXPENSES', 24, N'Expense'),
    (N'468', N'PUBLICATIONS/ADVERTISING', 24, N'Expense'),
    (N'470', N'OUTSIDE SERVICE - LAB FEES', 24, N'Expense'),
    (N'480.1', N'INSURANCE - WORKMAN''S COMP', 24, N'Expense'),
    (N'480.2', N'INSURANCE - TRASH TRUCK AND DUM', 24, N'Expense'),
    (N'50000', N'Cost of Goods Sold', 24, N'Expense');

MERGE INTO MunicipalAccounts AS target
USING @Coa AS source
ON target.AccountNumber = source.AccountNumber
WHEN MATCHED THEN
    UPDATE SET
        target.[Name] = source.[Name],
        target.[Type] = source.[Type],
        target.TypeDescription = source.TypeDescription,
        target.IsActive = 1,
        target.LastSyncDate = SYSUTCDATETIME()
WHEN NOT MATCHED BY TARGET THEN
    INSERT (DepartmentId, BudgetPeriodId, AccountNumber, [Name], [Type], TypeDescription, FundDescription, FundType, Balance, BudgetAmount, IsActive, LastSyncDate)
    VALUES (1, @ActiveBudgetPeriodId, source.AccountNumber, source.[Name], source.[Type], source.TypeDescription, N'General Fund', 0, 0, 0, 1, SYSUTCDATETIME());

SELECT @@ROWCOUNT AS RowsAffected;
