name: CI New

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pre-test Cloudflare diagnostics
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $hostName = $env:CLOUDFLARE_TUNNEL_HOST
          if (-not $hostName) { $hostName = 'example.invalid' }
          $port = if ($env:LOCAL_SERVICE_PORT) { [int]$env:LOCAL_SERVICE_PORT } else { 0 }
          $result = ./tools/cloudflare/diagnose-cloudflare-tunnel.ps1 -Hostname $hostName -Port $port -Verbose
          Write-Output "Diagnostic Summary: $($result | ConvertTo-Json -Compress)"

      - name: Build
        shell: pwsh
        run: |
          dotnet build .\WileyWidget.csproj --nologo /property:BuildIncremental=true

      - name: Test
        shell: pwsh
        run: |
          dotnet test .\WileyWidget.ViewModels.Tests.csproj --logger "trx;LogFileName=viewmodels-test-results.trx" --results-directory .\TestResults --no-build
          dotnet test .\WileyWidget.Services.Tests\WileyWidget.Services.Tests.csproj --logger "trx;LogFileName=services-test-results.trx" --results-directory .\TestResults --no-build

      - name: Upload Cloudflare logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cloudflare-diagnostics
          path: |
            logs/cloudflare/**
            TestResults/**
