name: RegionViewRegistry Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'WileyWidget.Tests/Regions/**'
      - 'src/Regions/**'
      - 'Dockerfile.regionviewregistry-tests'
      - 'docker-compose.regionviewregistry-tests.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'WileyWidget.Tests/Regions/**'
      - 'src/Regions/**'
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'
  TEST_RESULTS_PATH: './TestResults/RegionViewRegistry'

jobs:
  test-regionviewregistry:
    name: Run RegionViewRegistry Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore WileyWidget.Tests/WileyWidget.Tests.csproj
    
    - name: Build test project
      run: dotnet build WileyWidget.Tests/WileyWidget.Tests.csproj --configuration Release --no-restore
    
    - name: Note C# tests deprecated
      shell: pwsh
      run: |
        Write-Output "RegionViewRegistry xUnit tests are deprecated."
        Write-Output "Use Python tests under tools/python/tests/."

  test-regionviewregistry-docker:
    name: Run RegionViewRegistry Tests (Docker)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build MCP CI image
      run: docker build -f docker/Dockerfile.mcp-ci -t wiley-mcp-ci .

    - name: Build test image
      run: |
        docker build \
          -f Dockerfile.regionviewregistry-tests \
          --target test \
          -t wiley-regionviewregistry-tests:${{ github.sha }} \
          .
    
    - name: Run tests in Docker
      run: |
        docker run --rm \
          -v $(pwd)/${{ env.TEST_RESULTS_PATH }}:/testresults \
          wiley-regionviewregistry-tests:${{ github.sha }}
    
    - name: Start MCP Server
      run: docker run -d -p 8080:8080 --name wiley-mcp-ci wiley-mcp-ci
    
    - name: Register MCP Tools
      run: |
        sleep 5
        node scripts/mcp-client.js client register-tool --url http://localhost:8080/ --manifest ci-tools.json
    
    - name: Run .NET Tests
      run: dotnet test WileyWidget.sln
    
    - name: Run Python Tests
      run: cd tools/python/tests && pytest
    
    - name: AI Diagnostic with MCP
      run: |
        node scripts/mcp-client.js client call --url http://localhost:8080/ --tool-id get_build_logs --params '{"sha": "${{ github.sha }}"}'
        node scripts/mcp-client.js client call --url http://localhost:8080/ --tool-id analyze_xaml --params '{"path": "."}'
    
    - name: Upload Docker test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: regionviewregistry-docker-results
        path: ${{ env.TEST_RESULTS_PATH }}
        retention-days: 30

    - name: Stop MCP Server
      if: always()
      run: docker rm -f wiley-mcp-ci

