name: RegionViewRegistry Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'WileyWidget.Tests/Regions/**'
      - 'src/Regions/**'
      - 'Dockerfile.regionviewregistry-tests'
      - 'docker-compose.regionviewregistry-tests.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'WileyWidget.Tests/Regions/**'
      - 'src/Regions/**'
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'
  TEST_RESULTS_PATH: './TestResults/RegionViewRegistry'

jobs:
  test-regionviewregistry:
    name: Run RegionViewRegistry Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore WileyWidget.Tests/WileyWidget.Tests.csproj
    
    - name: Build test project
      run: dotnet build WileyWidget.Tests/WileyWidget.Tests.csproj --configuration Release --no-restore
    
    - name: Note C# tests deprecated
      shell: pwsh
      run: |
        Write-Output "RegionViewRegistry xUnit tests are deprecated."
        Write-Output "Use Python tests under tools/python/tests/."

  test-regionviewregistry-docker:
    name: Run RegionViewRegistry Tests (Docker)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build test image
      run: |
        docker build \
          -f Dockerfile.regionviewregistry-tests \
          --target test \
          -t wiley-regionviewregistry-tests:${{ github.sha }} \
          .
    
    - name: Run tests in Docker
      run: |
        docker run --rm \
          -v $(pwd)/${{ env.TEST_RESULTS_PATH }}:/testresults \
          wiley-regionviewregistry-tests:${{ github.sha }}
    
    - name: Upload Docker test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: regionviewregistry-docker-results
        path: ${{ env.TEST_RESULTS_PATH }}
        retention-days: 30

